### ISSUE TITLE
pooling的问题

### ISSUE THREAD

**Issue by congwupiece** [casuallyName/text-embeddings-inference-npu#1]
哈罗你好我根据您的这个流程走了一遍然后起embedding服务。但是我遇到一个问题哈。我测试的模型是m3e-base,然后他的1_Pooling里显示是pooling是mean，但是启动text-embeddings-router 的时候--pooling mean会直接报错。
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/3a783b52-cb2e-4c67-8ddc-520e642e97e2">
用cls能启动，但是我感觉预估的结果和transformer直接出并不一样，感觉值都非常小。请问下这个pooling选择是在模型compile的时候就确定的吗？然后它可用的值和模型里1_Pooling的为啥不一致呢？

**Comment by congwupiece** [comment]
我又看了一眼在https://github.com/casuallyName/text-embeddings-inference-npu/blob/main/backends/python/server/text_embeddings_server/server.py#L32

**Comment by congwupiece** [comment]
backend位置logger的embedding
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/d8e1ec5b-4d0d-4891-a685-dc0ceb33a66b">
api返回的embedding
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/a746e9e5-59b8-43bd-80bf-432cd09cbbb5">

**Comment by congwupiece** [comment]
似乎这里定义死了https://github.com/casuallyName/text-embeddings-inference-npu/blob/363b23ecfbc9e74d8eb7e6db3f07715e1677bd03/backends/python/src/lib.rs#L32 但是为啥如此呢？
<img width="904" alt="image" src="https://github.com/user-attachments/assets/cb37cc26-95b2-48de-a1da-f5537b5e4ec9">

**Comment by casuallyName** [comment]
`--pooling`的实际功能好像确实是TEI在合并了最近的几个PR后才实现的，在原始的版本里确实是如此定义的https://github.com/huggingface/text-embeddings-inference/blob/v1.2.3/backends/python/src/lib.rs#L33

**Comment by congwupiece** [comment]
我又看了眼代码 。我发现/embed接口个参数normalize。不设置大概默认是true。 设置成false输出就和模型直出一致了。大概是这个地方会的改写结果
<img width="970" alt="image" src="https://github.com/user-attachments/assets/8fec4dd2-1899-4623-8bd9-6a6953080649">
 
  https://github.com/casuallyName/text-embeddings-inference-npu/blob/363b23ecfbc9e74d8eb7e6db3f07715e1677bd03/core/src/infer.rs#L240

**Comment by casuallyName** [comment]
我参考[huggingface/text-embeddings-inference(Feature/python pooling #415)](https://github.com/huggingface/text-embeddings-inference/pull/415) 改了一版，推到了[python_pooling](https://github.com/casuallyName/text-embeddings-inference-npu/tree/python_pooling)分支，需要的话你可以切到这个分支重新安装一遍。

**Comment by congwupiece** [comment]
> 我参考[huggingface/text-embeddings-inference(Feature/python pooling #415)](https://github.com/huggingface/text-embeddings-inference/pull/415) 改了一版，推到了[python_pooling](https://github.com/casuallyName/text-embeddings-inference-npu/tree/python_pooling)分支，需要的话你可以切到这个分支重新安装一遍。

好的好的。 非常感谢🙏
